# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "xxx.xxx.xxx.xxx"
  config.ssh.insert_key = false
  config.vm.provision :shell, :path => "bootstrap.sh"

end
