---
resources:
- name: every-1m
  type: time
  source: {
    interval: 1m
  }

jobs:
- name: current-date
  plan:
  - get: every-1m
    trigger: true
  - task: echo-current-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {
          repository: busybox
        }
      run:
        path: date
        args: ["+%Y-%m-%d %H:%M:%S%z"]
